version: '3.4'

services:
  app-cups:
    image: fooius/app-cups:0.6
    build:
      context: .
    network_mode: host
    devices:
      - /dev/bus
    ports:
      - '631:631'
#    volumes:
#      - /var/run/dbus
