#! /bin/sh
### BEGIN INIT INFO
# Provides:          devicecontrollogserviced
# Required-Start:    
# Required-Stop:     
# Should-Start:      
# Should-Stop:       
# X-Start-Before:    
# X-Stop-After:      
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: devicecontrollog service deamon
### END INIT INFO

# export PCS_SETTING_DIR=
# export PCS_INSTALL_DIR=

DAEMON=/usr/sbin/devicecontrollogserviced
NAME=devicecontrollogserviced
DESC="devicecontrollog service deamon"
SCRIPT=epson_devicecontrollogserviced

test -x $DAEMON || exit 1

RETVAL=0

. /lib/lsb/init-functions

case "$1" in
  start)
	log_begin_msg "Starting $DESC: $DAEMON"	
	start-stop-daemon --start --quiet --oknodo  --exec $DAEMON 
	RETVAL=$?
	log_end_msg $?
	;;
  stop)
	log_begin_msg "Stopping $DESC: $DAEMON"	
	start-stop-daemon --stop --quiet --retry 5  --oknodo --exec $DAEMON
	RETVAL=$?
	log_end_msg $?	
	;;
  restart)
	/etc/init.d/$SCRIPT stop
 	/etc/init.d/$SCRIPT start
	;;
  *)
	N=/etc/init.d/${0##*/}
	echo "Usage: $N {start|stop|restart}" >&2
	exit 1
	;;
esac

exit $RETVAL
