#!/bin/sh

SRV_NAME=epson_pcsvcd
LOG_SRV_NAME=epson_devicecontrollogserviced

if [ "$1" = "configure" ] ; then
	update-rc.d $LOG_SRV_NAME start 20 2 3 4 5 . stop 80 0 1 6 .
	update-rc.d $SRV_NAME start 20 2 3 4 5 . stop 80 0 1 6 .

	/etc/init.d/$LOG_SRV_NAME start
	/etc/init.d/$SRV_NAME start

	exit 0
fi

