#!/bin/sh

THIS_VERSION=3.17.0.0-1

PCS_LNK=portcommunicationserviced
LOG_LNK=devicecontrollogserviced

SRV_NAME=epson_pcsvcd
LOG_SRV_NAME=epson_devicecontrollogserviced

OLD_OPT_DIR=/opt/epson/portcommunicationservice
OLD_VAR_DIR=/var/epson/portcommunicationservice
OLD_VAR_LOG_DIR=/var/epson/devicecontrollog

VAR_DIR=/var/epson_pcs/portcommunicationservice
VAR_LOG_DIR=/var/epson_pcs/devicecontrollog

PCS_SETTING=pcs.properties
LOG_SETTING=log.settings
LOG_FILE_NAME=log.txt
BACKUP_LOG_PATTERN=std*.gz

PCS_SOCKET=pcsvc.socket
LOG_SOCKET=logd.socket


if [ "$1" = "install" ] ; then
	exit 0
elif [ "$1" = "upgrade" ] ; then
	if dpkg --compare-versions "$2" gt "$THIS_VERSION" ; then
		exit 1
	fi

	/etc/init.d/$SRV_NAME stop
	/etc/init.d/$LOG_SRV_NAME stop

	update-rc.d -f $SRV_NAME remove
	update-rc.d -f $LOG_SRV_NAME remove

	rm -f /etc/init.d/$SRV_NAME
	rm -f /etc/init.d/$LOG_SRV_NAME
	killall -s SIGKILL /usr/sbin/$PCS_LNK 1>/dev/null 2>&1
	killall -s SIGTERM /usr/sbin/$LOG_LNK 1>/dev/null 2>&1

	if [ ! -e ${VAR_LOG_DIR} -a -e ${OLD_VAR_LOG_DIR} ] ; then
		mkdir -p -m 777 ${VAR_LOG_DIR}
		if [ -x ${OLD_OPT_DIR}/property-reader ] ; then
		        OLD_LOG_DIR=$(${OLD_OPT_DIR}/property-reader ${OLD_VAR_LOG_DIR}/${LOG_SETTING} Log.Path)
		        if [ "${OLD_LOG_DIR}" = "" ] ; then
			        cp -p ${OLD_VAR_LOG_DIR}/${BACKUP_LOG_PATTERN} ${VAR_LOG_DIR}/ 2>/dev/null || true
					if [ -e ${OLD_VAR_LOG_DIR}/${LOG_FILE_NAME} ] ; then
					        cp -p ${OLD_VAR_LOG_DIR}/${LOG_FILE_NAME} ${VAR_LOG_DIR}/${LOG_FILE_NAME}
					fi
				fi
		fi
		if [ -e ${OLD_VAR_LOG_DIR}/${LOG_SETTING} ] ; then
		        cp -p ${OLD_VAR_LOG_DIR}/${LOG_SETTING} ${VAR_LOG_DIR}/${LOG_SETTING}
		fi
	fi

	if [ ! -e ${VAR_DIR} -a -e ${OLD_VAR_DIR}/${PCS_SETTING} ] ; then
		mkdir -p -m 755 ${VAR_DIR}
	        cp -p ${OLD_VAR_DIR}/${PCS_SETTING} ${VAR_DIR}/${PCS_SETTING}
	fi

	if [ -e ${OLD_VAR_LOG_DIR} ] ; then
	    rm -f ${OLD_VAR_LOG_DIR}/${BACKUP_LOG_PATTERN}
	    rm -f ${OLD_VAR_LOG_DIR}/${LOG_FILE_NAME}
		rm -f ${OLD_VAR_LOG_DIR}/${LOG_SETTING}
		rm -f ${OLD_VAR_LOG_DIR}/${LOG_SOCKET}
		rmdir --ignore-fail-on-non-empty ${OLD_VAR_LOG_DIR}
	fi
	if [ -e ${OLD_VAR_DIR} ] ; then
	    rm -f ${OLD_VAR_DIR}/${PCS_SETTING}
		rm -f ${OLD_VAR_DIR}/${PCS_SOCKET}
	fi

	exit 0
fi

exit 1

